### ISSUE TITLE
Upgrade actions/upload-artifact calls to latest v4 (OSOE-809)

### ISSUE THREAD

**Issue by BenedekFarkas** [Lombiq/GitHub-Actions#329] opened 2024-02-13 13:26 UTC
As it brings a lot of improvements, [see the announcement](https://github.blog/2024-02-12-get-started-with-v4-of-github-actions-artifacts/).

See [its usages across the Lombiq organization](https://github.com/search?q=org%3ALombiq+%22actions%2Fupload-artifact@%22&type=code).

Any particular reason we don't have a wrapper action yet?

[Jira issue](https://lombiq.atlassian.net/browse/OSOE-809)

**Comment by Piedone** [comment] 2024-02-13 13:53
Duplicate of: https://github.com/Lombiq/GitHub-Actions/issues/272. I added a note there to also have a wrapper.

**Closed as not planned by Piedone** 2024-02-13 13:53 UTC
Labels: enhancement

**Comment by BenedekFarkas** [comment] 2024-02-13 14:26
OK then! AFAIK we don't have any usages of it where the time reduction would be of huge impact right now (= not having to wait that much + runner cost). The only exception is a client project that I just upgraded and uploading a 500-something MB artifact took 21 seconds instead of 2 and a half minutes, which is great.

**Comment by Piedone** [comment] 2024-02-13 14:35
Yeah, that'll be nice but not crucial. Most of our projects only upload artifacts on some failure anyway.
